#!/bin/sh
# postrm script for prometheus-exporter-exporter
# Script executed after the package is removed.

set -e

case "$1" in
  purge)
    rm -rf /var/log/prometheus/prometheus-exporter-exporter.log \
            /var/log/prometheus/prometheus-exporter-exporter.log.* \
            /var/run/prometheus/prometheus-exporter-exporter.pid

    # We do NOT remove the system user.
  ;;
esac

#DEBHELPER#
